//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public int ORDER_ID { get; set; }
        public int WORK_ORDER_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string STATUS_NAME { get; set; }
        public string MODEL_NAME { get; set; }
        public string NOTES { get; set; }
        public Nullable<System.DateTime> REPAIR_DATE { get; set; }
    }
}
