//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCost
    {
        public int WORK_ORDER_ID { get; set; }
        public string PART_NAME { get; set; }
        public string PRICE { get; set; }
        public Nullable<double> QTY { get; set; }
    }
}
